### ISSUE TITLE
Compilation Issue with LittleFS_esp32 in Bombercat Project: 'LittleFS.h' file not found - WifiWebServer.ino

### ISSUE THREAD

**Issue by roozea** [ElectronicCats/BomberCat#26]
Hello,

I'm currently working on the Bombercat project and encountered a compilation issue related to the **LittleFS_esp32 library by lorol**. My aim was to integrate **WifiWebServer.ino** functionality into the project, but despite correctly installing the LittleFS_esp32 library, the compiler is unable to locate the 'LittleFS.h' file.

**Environment:**
- Operating System: macOS Sonoma 14
- Arduino IDE: Arduino IDE 2.3.2
- LittleFS_esp32 Library Version: 1.0.6

**Error Message:**
In file included from /Users/[username]/Documents/Arduino/libraries/Preferences/src/Preferences.cpp:64:0:
/Users/[username]/Documents/Arduino/libraries/Preferences/src/prefs_impl_arduino.h:2:12: fatal error: LittleFS.h: No such file or directory
#include "LittleFS.h"
^~~~~~~~~~~~

**Steps to Reproduce:**
1. Installed the LittleFS_esp32 library via the Arduino IDE's Library Manager aiming to use it for the Bombercat project.
2. Tried to compile the Bombercat project which includes integration of the WifiWebServer, with the line `#include <LittleFS.h>` in the sketch.

**Troubleshooting Attempts:**
- Verified that the LittleFS_esp32 library is installed correctly in the Arduino libraries directory.
- Restarted the Arduino IDE after installing the library.

Despite these efforts, the issue persists, preventing successful compilation. I'm looking for insights or any additional steps I might be missing to ensure that the LittleFS_esp32 library is correctly recognized during the compilation process, especially in the context of integrating WifiWebServer into the Bombercat project.

Thank you in advance for your support and guidance.

Best regards,
Roozea

**Comment by xpeqex** [comment]
Hi @roozea 

Thank you for bringing this to our attention.

This error you are facing may be due to the Preference library you are using. While in the sketch there is a link and the instructions indicates the version should be 2.1.0, you must go to [ElectronicCats/Preferences ](https://github.com/ElectronicCats/Preferences) and download the library by creating a copy of the repo and not downloading the library from the releases section. 

In any case, here is the direct link to download the library: [Preferences.zip](https://github.com/ElectronicCats/Preferences/archive/refs/heads/main.zip). Please download the library, replace the current files and try again.

Lastly, be assured we will modify the instructions for clearer understanding.
Let me know if this solves the problem.
😼

**Comment by roozea** [comment]
Hello,

I wanted to extend my gratitude for your prompt and helpful response. Following your instructions, I downloaded the correct version of the Preferences library from ElectronicCats/Preferences, replaced the existing files, and I can confirm that this has resolved the compilation issue I was facing.

I greatly appreciate your willingness to modify the instructions to make them clearer, which will surely help to avoid similar confusion in the future.

Thank you again for your support and the provided solution.

Best regards,
@roozea

**Comment by xpeqex** [comment]
Hey @roozea 

I am glad to read this was the issue!

Please be assure we will modify this in the instructions and the wiki to make it clearer. 

Feel free to reach out to us again.

 
<p align=right>
<img src="https://github.com/ElectronicCats/mpu6050/assets/107638696/e68784a5-ef53-4fbd-93df-cacb582cdec2" width=150 />
</p>
